#############################################################################
#
#   Copyright (C) Microsoft Corporation 1992-1997
#   All Rights Reserved.
#
#   makefile for first
#
#############################################################################

!IF 0
Copyright (C) Microsoft Corporation 1992-1997
Module Name:
	makefile

Notes:

!ENDIF
!INCLUDE $(NTMAKEENV)\makefile.def


